---
name: default
kind: pipeline
type: kubernetes

steps:
  - name: xen-almalinux
    image: ubuntu
    #network_mode: host
    #privileged: true
    commands:
       - apt update
       - apt install -y iproute2
       - ip a
       - sleep 3600
