kind: pipeline
type: docker
name: build
steps:
  - name: dummy-echo
    image: alpine:latest
    commands:
      - echo "build step taking 10s."
      - sleep 30
---
kind: pipeline
type: docker
name: test
steps:
  - name: dummy-echo
    image: alpine:latest
    commands:
      - echo "build step taking 10s."
      - sleep 30
depends_on:
  - build
---
kind: pipeline
type: docker
name: tools
steps:
  - name: dummy-echo
    image: alpine:latest
    commands:
      - echo "build step taking 10s."
      - sleep 30
depends_on:
  - test
---
kind: pipeline
type: docker
name: deploy
steps:
  - name: dummy-echo
    image: alpine:latest
    commands:
      - echo "build step taking 10s."
      - sleep 30
depends_on:
  - tools
---
kind: pipeline
type: docker
name: perf
steps:
  - name: dummy-echo
    image: alpine:latest
    commands:
      - echo "build step taking 10s."
      - sleep 30
depends_on:
  - deploy