---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: ubuntu:latest
  network_mode: host
  privileged: true
  commands:
  - apt update
  - apt install ssh-client -y
  - ssh harness@192.168.10.253
