kind: pipeline
type: exec
name: test
steps:
  - name: dummy-echo
    commands:
      - echo "build step taking 10s. on Branch feature/test1"
      - sleep 360
    when:
      branch:
      - dev
      event:
      - push
---
kind: pipeline
type: exec
name: perf
steps:
  - name: dummy-echo pipeline exec
    commands:
      - echo "build step taking 10s. on Branch feature/test1"
      - sleep 360
branch:
  include:
    - dev
