kind: pipeline
type: docker
name: test
steps:
  - name: dummy-echo
    commands:
      - echo "build step taking 10s."
      - sleep 30
---
kind: pipeline
type: docker
name: perf
steps:
  - name: dummy-echo
    commands:
      - echo "build step taking 10s."
      - sleep 30
