---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: alpine:3.8
  commands:
  - apk add curl
  - sleep 45
  - curl http://172.17.0.1:9200
  network_mode: host
  privileged: true

services:
- name: database
  image: elasticsearch:5-alpine
  network_mode: host
  privileged: true
