kind: pipeline
type: exec
name: test
steps:
  - name: dummy-echo
    commands:
      - echo "build step taking 10s. on Branch feature/devtest1"
      - sleep 10
---
kind: pipeline
type: exec
name: perf
steps:
  - name: dummy-echo pipeline exec
    commands:
      - echo "build step taking 10s. on Branch feature/devtest1"
      - sleep 10
