---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: alpine:3.8
  network_mode: host
  privileged: true
  commands:
  - apk add curl
  - sleep 45
  - curl http://localhost:9200

services:
- name: database
  image: elasticsearch:5-alpine
