global-variables:
  test_command: &test_command 'echo teste as command'
kind: pipeline
type: exec
name: test
steps:
  - name: dummy-echo
    commands:
      - echo "build step taking 10s."
      - sleep 30
---
kind: pipeline
type: exec
name: perf
steps:
  - name: dummy-echo
    commands:
      - echo "build step taking 10s."
      - sleep 30
