kind: pipeline
type: docker
name: build
steps:
  - name: dummy-echo
    image: alpine:latest
    commands:
      - echo VAR1=`cat var-files | grep -i duck` > .env
      - echo VAR2=`cat var-files | grep -i ^o` >> .env
      - echo VAR3=`cat var-files | grep -i do` >> .env
      - echo VAR4=`cat var-files | grep -i cat | cut -f1 -d " "` >> .env
  - name: read-vars
    image: alpine:latest
    commands:
      - source .env
      - echo $VAR1
      - echo $VAR2
      - echo $VAR3
      - echo $VAR4
kind: pipeline
type: docker
name: test
steps:
  - name: dummy-echo
    image: alpine:latest
    commands:
      - echo "build step taking 10s."
      - sleep 30
---
kind: pipeline
type: docker
name: tools
steps:
  - name: dummy-echo
    image: alpine:latest
    commands:
      - echo "build step taking 10s."
      - sleep 30
---
kind: pipeline
type: docker
name: deploy
steps:
  - name: dummy-echo
    image: alpine:latest
    commands:
      - echo "build step taking 10s."
      - sleep 30
---
kind: pipeline
type: docker
name: perf
steps:
  - name: dummy-echo
    image: alpine:latest
    commands:
      - echo "build step taking 10s."
      - sleep 30