---
kind: pipeline
type: docker
name: ubuntu
clone:
  disable: true
steps:
  - name: drone test
    image: ubuntu
    commands:
      - base64 /dev/urandom | head -c 10000000 > file.txt
      - cat file.txt
      - /bin/false
