kind: pipeline
type: exec
name: test
steps:
  - name: dummy-echo
    commands:
      - echo "build step taking 10s. on Branch feature/test"
      - sleep 30
    when:
      branch:
      - main
      event:
      - push
---
kind: pipeline
type: exec
name: perf
steps:
  - name: dummy-echo pipeline exec
    commands:
      - echo "build step taking 10s. on Branch feature/test"
      - sleep 30
    when:
      branch:
      - main
      event:
      - push
      - pull_request
